#定义端口
server:
  port: 8888

#连接数据库mysql配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://8.137.36.141:3307/familymaptest?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: iamcool616..

